<script setup>
</script>

<template>
  <div class="min-h-screen bg-gradient-to-b from-emerald-50 via-white to-teal-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-4xl mx-auto bg-white p-8 sm:p-12 pl-10 shadow-xl rounded-2xl border border-gray-200">
      <!-- Header -->
      <div class="mb-12 text-center">
        <h1 class="text-4xl md:text-5xl font-bold text-teal-800 mb-2">
          Terms and Conditions
        </h1>
        <p class="text-lg text-teal-600">For YourView</p>
        <p class="text-sm text-gray-500 mt-1">Last updated: October 2025</p>
      </div>

      <!-- Sections -->

      <!-- Introduction -->
      <section id="introduction" class="mb-12">
        <h2 class="text-2xl font-bold text-emerald-700 mb-4">1. Introduction</h2>
        <div class="space-y-4 text-gray-700 leading-relaxed">
          <p>Welcome to <span class="font-semibold text-emerald-800">YourView</span>. These Terms govern your use of our website and services. By accessing or using YourView, you agree to be bound by these Terms.</p>
          <p>If you do not agree with any part of these terms, you must not use our service.</p>
        </div>
        <hr class="border-t-2 border-gradient-to-r from-emerald-200 via-teal-300 to-emerald-200 my-8" />
      </section>

      <!-- Services -->
      <section id="services" class="mb-12">
        <h2 class="text-2xl font-bold text-teal-700 mb-4">2. Our Services</h2>
        <div class="space-y-4 text-gray-700 leading-relaxed">
          <p>YourView provides several services designed to help users understand and improve their urban environment:</p>
          <ul class="list-disc list-inside space-y-2 pl-2">
            <li><strong>Window Photo Analysis:</strong> Evaluate your view and access to nature.</li>
            <li><strong>Plant Health Analysis:</strong> AI-generated plant care recommendations.</li>
            <li><strong>Suburb Heat Map:</strong> See local heat variations across Melbourne.</li>
            <li><strong>Window Gallery:</strong> Share photos optionally with the community.</li>
          </ul>
        </div>
        <hr class="border-t-2 border-gradient-to-r from-teal-200 via-emerald-300 to-teal-200 my-8" />
      </section>

      <!-- User Content -->
      <section id="user-content" class="mb-12">
        <h2 class="text-2xl font-bold text-emerald-700 mb-4">3. User Content & Photo Uploads</h2>
        <div class="space-y-4 text-gray-700 leading-relaxed">
          <p>You retain ownership of photos or content you upload. By uploading, you grant YourView a license to use content to provide and improve services.</p>
          <p>Do not upload illegal content or materials infringing on privacy or copyright.</p>
        </div>
        <hr class="border-t-2 border-gradient-to-r from-emerald-200 via-teal-300 to-emerald-200 my-8" />
      </section>

      <!-- Plant Health Disclaimer -->
      <section id="disclaimers" class="mb-12">
        <h2 class="text-2xl font-bold text-teal-700 mb-4">4. Disclaimers & Limitations</h2>
        <div class="space-y-4 text-gray-700 leading-relaxed">
          <p><strong>Plant Health Feature:</strong> Advice is for informational purposes only and generated by AI.</p>
          <p><strong>General Service:</strong> Services are "as is." Accuracy of scores/maps not guaranteed. YourView is not liable for damages from use.</p>
        </div>
        <hr class="border-t-2 border-gradient-to-r from-teal-200 via-emerald-300 to-teal-200 my-8" />
      </section>

      <!-- Gallery -->
      <section id="gallery" class="mb-12">
        <h2 class="text-2xl font-bold text-emerald-700 mb-4">5. Window Gallery</h2>
        <div class="space-y-4 text-gray-700 leading-relaxed">
          <p>If you submit your photo to the public gallery, you grant permission to display it. You can request removal anytime.</p>
        </div>
        <hr class="border-t-2 border-gradient-to-r from-emerald-200 via-teal-300 to-emerald-200 my-8" />
      </section>

      <!-- Accessibility -->
      <section id="accessibility" class="mb-12">
        <h2 class="text-2xl font-bold text-emerald-700 mb-4">7. Accessibility</h2>
        <div class="space-y-4 text-gray-700 leading-relaxed">
          <p>YourView aims to make services accessible for all users. If you face accessibility issues, contact support for assistance.</p>
        </div>
        <hr class="border-t-2 border-gradient-to-r from-emerald-200 via-teal-300 to-emerald-200 my-8" />
      </section>

      <!-- Cookies Policy -->
      <section id="cookies" class="mb-12">
        <h2 class="text-2xl font-bold text-teal-700 mb-4">8. Cookies Policy</h2>
        <div class="space-y-4 text-gray-700 leading-relaxed">
          <p>We use cookies to enhance your experience. By using the service, you agree to the use of cookies as described in our Cookies Policy.</p>
        </div>
        <hr class="border-t-2 border-gradient-to-r from-teal-200 via-emerald-300 to-teal-200 my-8" />
      </section>

      <!-- Governing Law -->
      <section id="governing-law" class="mb-12">
        <h2 class="text-2xl font-bold text-emerald-700 mb-4">9. Governing Law</h2>
        <div class="space-y-4 text-gray-700 leading-relaxed">
          <p>These Terms are governed by the laws of Victoria, Australia. Any disputes will be handled under Victorian jurisdiction.</p>
        </div>
        <hr class="border-t-2 border-gradient-to-r from-emerald-200 via-teal-300 to-emerald-200 my-8" />
      </section>

      <!-- Contact -->
      <section id="contact" class="mb-12">
        <h2 class="text-2xl font-bold text-teal-700 mb-4">10. Contact Us</h2>
        <div class="space-y-4 text-gray-700 leading-relaxed">
          <p>Questions? Contact us at 
            <a href="mailto:support@yourview.com" class="text-blue-600 hover:underline">support@yourview.com</a>.
          </p>
        </div>
      </section>
    </div>
  </div>
</template>
